echo $D >> e.yaml
echo $FILE >> e.yaml
echo $FB_D_E >> e.yaml
echo $FB_D_U >> e.yaml
echo $FB_E_E >> e.yaml
echo $FB_E_U >> e.yaml
echo $TY >> e.yaml
echo $PN >> e.yaml
echo $REG >> e.yaml
echo $RES >> e.yaml
echo $SIE >> e.yaml
echo $SIU >> e.yaml
echo $FTYPE >> e.yaml
