#!/bin/bash
VENDOR=mediatek
PRODUCTS=wiko
ANDROID_TOP=/opt/android
LOL=$(dirname $0)
if [ -d $LOL/proprietary ];then
rm *.mk &>/dev/null
rm proprietary/*.mk &>/dev/null
rm $ANDROID_TOP/device/mediatek/wiko/proprietary-files.txt &>/dev/null
echo "####################################################################################"
echo -e "#\t\t\t\tAndroidProduct.mk\t\t\t\t\t\t#"
echo "####################################################################################"
cat << EOF >> Android.mk
# Copyright (C) 2014 The Android Open Source Project
# Create by Seifer Cross <roliya@163.com>
# 09/18/2014 - 04:28:34 CTS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by vendor/\$VENDOR/\$PRODUCTS/pcopy.sh

LOCAL_PATH := \$(call my-dir)

include \$(call all-makefiles-under, \$(LOCAL_PATH))
EOF


cat << EOF >> AndroidProduct.mk
# Copyright (C) 2014 The Android Open Source Project
# Create by Seifer Cross <roliya@163.com>
# 09/18/2014 - 04:28:34 CTS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by vendor/\$VENDOR/\$PRODUCTS/pcopy.sh

LOCAL_PATH := \$(call my-dir)

EOF

echo "####################################################################################"
echo -e "#\t\t\t\tvendor.mk\t\t\t\t\t\t#"
echo "####################################################################################"
cat << EOF >> wiko-vendor.mk
# Copyright (C) 2014 The Android Open Source Project
# Create by Seifer Cross <roliya@163.com>
# 09/18/2014 - 04:28:34 CTS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by vendor/\$VENDOR/\$PRODUCTS/pcopy.sh

-include vendor/mediatek/wiko/wiko-vendor-blobs.mk

EOF
echo "####################################################################################"
echo -e "#\t\t\t\tvendor-blobs.mk\t\t\t\t\t\t#"
echo "####################################################################################"
cat << EOF >> wiko-vendor-blobs.mk
# Copyright (C) 2014 The Android Open Source Project
# Create by Seifer Cross <roliya@163.com>
# 09/18/2014 - 04:28:34 CTS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by vendor/\$VENDOR/\$PRODUCTS/pcopy.sh

LOCAL_PATH := \$(call my-dir)

PRODUCT_COPY_FILES += \\
EOF

cat << EOF >> AndroidP.mk
# Copyright (C) 2014 The Android Open Source Project
# Create by Seifer Cross <roliya@163.com>
# 09/18/2014 - 04:28:34 CTS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by vendor/\$VENDOR/\$PRODUCTS/pcopy.sh

LOCAL_PATH := \$(call my-dir)

LOCAL_OVERRIDES_PACKAGES += \\
EOF

cat << EOF >> BoardConfigVendor.mk
# Copyright (C) 2014 The Android Open Source Project
# Create by Seifer Cross <roliya@163.com>
# 09/18/2014 - 04:28:34 CTS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by vendor/\$VENDOR/\$PRODUCTS/pcopy.sh

EOF

for LST in `find proprietary -type f -not -name "*.mk"`
do
echo "include \$(CLEAR_VARS)" >> AndroidProduct.mk
NAME=`echo $LST | NF \/`
OVER=`echo $LST | awk -F"/" '{ if($2 != "etc") {print "1"} else if($2 == "etc") {print "2"} }'`
MOD=`echo $NAME | sed 's/\.so//g' | sed 's/\.ko//g'`
echo "# $NAME" >> AndroidProduct.mk
echo "LOCAL_MODULE := $MOD" >> AndroidProduct.mk
echo "LOCAL_ADDITIONAL_DEPENDENCIES := \$(LOCAL_PATH)/over-vendor.mk" >> AndroidProduct.mk
echo "LOCAL_SRC_FILES := vendor/$VENDOR/$PRODUCTS/$LST" >> AndroidProduct.mk
echo $LST | \
awk -F"/" '{
 if($2 == "lib")
 {
   CLS = "SHARED_LIBRARIES"
   tpath = "\\$\\(TARGET_OUT\\)/"CLS
   SUFF = ".so"
 }

 if($2 == "vendor")
 {
   CLS = "VENDOR_SHARED_LIBRARIES"
   tpath = "\\$\\(TARGET_OUT\\)/"CLS
   SUFF = ".so"
 }

 if($2 == "app")
 {
   CLS = "APPS"
   tpath = "\\$\\(TARGET_OUT\\)/"CLS
   SUFF = ".apk"
 }

 if($2 == "framework")
  {
   CLS = "JAVA_LIBRARIES"
   tpath = "\\$\\(TARGET_OUT\\)/"CLS
   SUFF = ".jar"
  }

 if($2 == "etc")
 {
  CLS = "ETC"
  tpath = "\\$\\(TARGET_OUT\\)/"CLS
  SUFF = ""
 }

 if($2 == "bin")
 {
  CLS = "EXECUTABLES"
  tpath = "\\$\\(TARGET_OUT\\)/"CLS
  SUFF = ""
  }

 if($2 == "xbin")
 {
   CLS = "OPTIONAL_EXECUTABLES"
   tpath = "\\$\\(TARGET_OUT\\)/"CLS
   SUFF = ""
 }

 if($2 == "usr" && $3 == "keylayout")
 {
  CLS = "KEYLAYOUT"
  tpath = "\\$\\(TARGET_OUT\\)/"CLS
  SUFF = ".kl"
 }

 if($2 == "usr" && $3 == "keychars")
 {
  CLS = "KEYCHARS"
  tpath = "\\$\\(TARGET_OUT\\)/"CLS
  SUFF = ".kcm"
 }

 if($2 == "usr" && $3 == "icu")
 {
  CLS = ""
  tpath = "\\$\\(TARGET_OUT\\)/../system/usr/icu"
  SUFF = ".icu"
 }

 if($2 == "usr" && $3 == "idc")
 {
 CLS = ""
 tpath = "\\$\\(TARGET_OUT\\)/../system/usr/idc"
 SUFF = ".icu"
 }
}
{
system("echo LOCAL_MODULE_CLASS := " CLS " >> AndroidProduct.mk")
system("echo LOCAL_MODULE_PATH := " tpath " >> AndroidProduct.mk")
system("echo LOCAL_MODULE_SUFFIX := " SUFF " >> AndroidProduct.mk")
}'

echo "LOCAL_MODULE_TAGS := optional" >> AndroidProduct.mk
echo "LOCAL_MODULE_OWNER := MTK" >> AndroidProduct.mk
echo "include \$(BUILD_PREBUILT)" >> AndroidProduct.mk
echo " " >> AndroidProduct.mk
TAT=`echo $LST | sed 's/proprietary\///g'`
echo -e "\t\$(LOCAL_PATH)/$LST:system/$TAT \\" >> wiko-vendor-blobs.mk
echo "$TAT" >> $ANDROID_TOP/device/mediatek/wiko/proprietary-files.txt
if [ $OVER == "1" ]; then
echo -e "\t\t$MOD \\" >> AndroidP.mk
fi
done

echo -e "\ninclude \$(BUILD_PREBUILT)" >> wiko-vendor-blobs.mk
##echo -e "\nLOCAL_RENDERSCRIPT_INCLUDES_OVERRIDE := \$(LOCAL_PATH)/over-vendor.mk" >> AndroidP.mk
echo -e "\ninclude \$(BUILD_PREBUILT)" >> AndroidP.mk
echo -e "\n-include mediatek/build/android/base_rules.mk" >> AndroidP.mk


mv AndroidP.mk proprietary/Android.mk
mv AndroidProduct.mk proprietary/over-vendor.mk
else
echo "Must chdir vendor/prj/drv and hava \"proprietary\" folder !"
fi
